# src/lpmo_pipeline/report/build_report_html.py
"""
Responsibility: Generate human-readable HTML report from summary + metrics.
Input:  summary.json, metrics.csv, tuning summary (optional)
Output: report.html

Sections:
  1. Pipeline info (version, timestamp, config)
  2. Dataset overview (tables, pose counts)
  3. QC summary (pass rates, error distributions)
  4. Cluster landscape (distributions, stability)
  5. Geometry distributions (Cu–C1/C4, His-brace)
  6. Crystal comparison (if available)
  7. CBM analysis (if DEL B)
  8. Tuning results (if tuning mode)
"""
from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Minimal HTML template (Jinja2-style placeholders in pseudocode)
HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>LPMO Pipeline Report — {run_id}</title>
  <style>
    body {{ font-family: sans-serif; margin: 2em; line-height: 1.5; }}
    h1 {{ color: #2c3e50; }}
    h2 {{ color: #34495e; border-bottom: 1px solid #ccc; padding-bottom: 0.3em; }}
    table {{ border-collapse: collapse; margin: 1em 0; }}
    th, td {{ border: 1px solid #ddd; padding: 0.5em 1em; text-align: left; }}
    th {{ background: #f5f5f5; }}
    .pass {{ color: green; font-weight: bold; }}
    .fail {{ color: red; font-weight: bold; }}
    .flag {{ color: orange; }}
  </style>
</head>
<body>

<h1>LPMO Structure Prediction Pipeline Report</h1>
<p><strong>Run:</strong> {run_id} | <strong>Mode:</strong> {mode} | <strong>Timestamp:</strong> {timestamp}</p>

<h2>1. Dataset Overview</h2>
<table>
  <tr><th>Proteins</th><td>{n_proteins}</td></tr>
  <tr><th>Ligands</th><td>{n_ligands}</td></tr>
  <tr><th>Models</th><td>{n_models}</td></tr>
  <tr><th>Total poses</th><td>{n_poses}</td></tr>
</table>

<h2>2. QC Summary</h2>
<table>
  <tr><th>Total QC'd</th><td>{qc_total}</td></tr>
  <tr><th>Passed</th><td class="pass">{qc_passed}</td></tr>
  <tr><th>Flagged</th><td class="flag">{qc_flagged}</td></tr>
  <tr><th>Dropped</th><td class="fail">{qc_dropped}</td></tr>
  <tr><th>Pass rate</th><td>{qc_pass_rate:.1%}</td></tr>
</table>

<h2>3. Cluster Landscape</h2>
<p>Mean clusters per protein×ligand: {mean_clusters:.1f}</p>
<p>Mean outlier rate: {mean_outlier:.1%}</p>
<!-- PLACEHOLDER: cluster distribution plot (matplotlib/plotly embed or image) -->

<h2>4. Geometry</h2>
<p>Cu–C1 range: {cu_c1_range}</p>
<p>Cu–C4 range: {cu_c4_range}</p>
<!-- PLACEHOLDER: geometry distribution histograms -->

{crystal_section}

{cbm_section}

{tuning_section}

<hr>
<p><em>Generated by LPMO Pipeline v2.1</em></p>
</body>
</html>
"""


def build_report_html(
    summary: dict[str, Any],
    metrics_csv_path: Path,
    output_path: Path,
    tuning_data: dict[str, Any] | None = None,
) -> None:
    """Generate HTML report.

    Args:
        summary: Loaded summary.json dict.
        metrics_csv_path: Path to metrics.csv (for detailed tables).
        output_path: Output HTML path.
        tuning_data: Optional formatted tuning data (from tune_summarize).
    """
    ds = summary.get("dataset_stats", {})
    qc = summary.get("qc_stats", {})
    cs = summary.get("cluster_stats", {})
    gs = summary.get("geometry_stats", {})

    # Crystal section
    crystal_section = ""
    if "crystal_stats" in summary:
        xs = summary["crystal_stats"]
        crystal_section = f"""
<h2>5. Crystal Comparison</h2>
<p>N comparisons: {xs.get('n_comparisons', 0)}</p>
<p>Mean best Tanimoto: {xs.get('mean_best_tanimoto', 0.0):.3f}</p>
"""

    # CBM section
    cbm_section = ""
    if summary.get("del_variant") == "b":
        cbm_section = """
<h2>6. CBM Analysis (DEL B)</h2>
<p>See cbm_metrics/ for paired comparison DEL A vs DEL B.</p>
"""

    # Tuning section
    tuning_section = ""
    if tuning_data:
        rows_html = ""
        for row in tuning_data.get("table_data", []):
            marker = " ★" if row.get("is_best") else ""
            rows_html += (
                f"<tr><td>{row['phase']}</td>"
                f"<td>{row['param_hash']}{marker}</td>"
                f"<td>{row['qc_pass_rate']:.2f}</td>"
                f"<td>{row['outlier_rate']:.3f}</td>"
                f"<td>{row['mean_n_clusters']:.1f}</td>"
                f"<td>{row['crystal_sim']:.3f}</td></tr>\n"
            )
        tuning_section = f"""
<h2>Tuning Results</h2>
<p>{tuning_data.get('decision_rationale', '')}</p>
<table>
  <tr><th>Phase</th><th>Params</th><th>QC pass</th><th>Outlier</th><th>Clusters</th><th>Crystal</th></tr>
  {rows_html}
</table>
"""

    html = HTML_TEMPLATE.format(
        run_id=summary.get("run_id", ""),
        mode=summary.get("mode", ""),
        timestamp=summary.get("timestamp", ""),
        n_proteins=ds.get("n_proteins", 0),
        n_ligands=ds.get("n_ligands", 0),
        n_models=ds.get("n_models", 0),
        n_poses=ds.get("n_total_poses", 0),
        qc_total=qc.get("total_poses_qc", 0),
        qc_passed=qc.get("passed", 0),
        qc_flagged=qc.get("flagged", 0),
        qc_dropped=qc.get("dropped", 0),
        qc_pass_rate=qc.get("pass_rate", 0.0),
        mean_clusters=cs.get("mean_n_clusters", 0.0),
        mean_outlier=cs.get("mean_outlier_rate", 0.0),
        cu_c1_range=gs.get("cu_c1_range", "N/A"),
        cu_c4_range=gs.get("cu_c4_range", "N/A"),
        crystal_section=crystal_section,
        cbm_section=cbm_section,
        tuning_section=tuning_section,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write(html)
    logger.info("Wrote HTML report to %s", output_path)
